mutation UpdateCanvas(
  $canvasId: ID!
  $name: String
  $previewImage: Upload
  $removePreview: Boolean!
) {
  updateCanvas(
    canvasId: $canvasId
    name: $name
    previewImage: $previewImage
    removePreview: $removePreview
  ) {
    id
    name
    previewSrc
  }
}
