mutation CreateCard(
  $boardId: ID!
  $clientMutationId: ID!
  $clientId: ID!
  $title: String!
  $container: CardContainer!
  $columnId: ID
  $index: Int!
) {
  createCard(
    boardId: $boardId
    clientMutationId: $clientMutationId
    clientId: $clientId
    title: $title
    container: $container
    columnId: $columnId
    index: $index
  )
}
