mutation RenameColumn($boardId: ID!, $clientMutationId: ID!, $columnId: ID!, $title: String!) {
  renameColumn(
    boardId: $boardId
    clientMutationId: $clientMutationId
    columnId: $columnId
    title: $title
  )
}
