mutation UpdateCard($boardId: ID!, $clientMutationId: ID!, $cardId: ID!, $patch: CardPatchInput!) {
  updateCard(boardId: $boardId, clientMutationId: $clientMutationId, cardId: $cardId, patch: $patch)
}
