mutation UpdateBoard(
  $boardId: ID!
  $name: String
  $previewImage: Upload
  $removePreview: Boolean!
) {
  updateBoard(
    boardId: $boardId
    name: $name
    previewImage: $previewImage
    removePreview: $removePreview
  ) {
    id
    name
    previewSrc
  }
}
