type User {
  id: ID!
  email: String!
}

type AuthResponse {
  user: User!
}

type Mutation {
  login(email: String!, password: String!): AuthResponse!
  register(email: String!, password: String!): AuthResponse!
  logout: Boolean!
  refreshSession: Boolean!
}

type Query {
  me: User
}
